<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.believe</groupId>
        <artifactId>believe-framework</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>believe-common-security</artifactId>
    <packaging>jar</packaging>

    <name>Believe Common Security</name>
    <description>加解密工具、JWT工具、安全相关基础封装</description>

    <dependencies>
        <dependency>
            <groupId>com.believe</groupId>
            <artifactId>believe-common-core</artifactId>
        </dependency>
    </dependencies>
</project>
