spring:
  application:
    name: believe-user
  profiles:
    active: dev

server:
  port: 8201

management:
  server:
    port: 8202
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.believe.user: DEBUG
