spring:
  config:
    import: optional:nacos:${spring.application.name}.yaml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: dev
      config:
        server-addr: nacos:8848
        namespace: dev
        file-extension: yaml
        # 声明共享配置列表
        shared-configs:
          - data-id: common-redis.yaml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: common-datasource.yaml
            group: DEFAULT_GROUP
            refresh: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/believe?useUnicode=true&characterEncoding=utf8mb4
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver