spring:
  application:
    name: believe-auth
  profiles:
    active: dev

server:
  port: 8101

management:
  server:
    port: 8102
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

sa-token:
  token-name: Authorization
  timeout: 7200
  activity-timeout: 1800
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
  jwt-secret-key: ${JWT_SECRET:believe-jwt-secret-key}

logging:
  level:
    com.believe.auth: DEBUG
